server:
  port: 8084

logging:
  file:
    name: logs/subscriber.log

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: telecom
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    initialization-mode: always
    continue-on-error: false
    hikari:
      jdbc-url: ${spring.datasource.url}
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      maximumPoolSize: 5
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}